name: finance-dashboard
channels:
  - conda-forge
dependencies:
  - python=3.11
  - streamlit>=1.35
  - yfinance>=0.2.40
  - pandas>=2.2
  - numpy>=1.26
  - plotly>=5.22
  - python-dateutil>=2.9
  - requests
  - pytz
  - kaleido